;;; ycm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ycm.el

(autoload 'ycm-query-completions "ycm" "\
Queries YCMD for completions, then calls callback with the results.

(fn CALLBACK)")
(register-definition-prefixes "ycm" '("ycm-"))

;;; End of scraped data

(provide 'ycm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ycm-autoloads.el ends here
